CREATE TYPE status_solicitacoes AS ENUM('ABERTA', 'EM_ATENDIMENTO', 'CONCLUIDA');

CREATE TABLE usuarios (
  id BIGSERIAL PRIMARY KEY,
  nome VARCHAR(255) NOT NULL,
  email VARCHAR(255) UNIQUE NOT NULL,
  senha VARCHAR(255) NOT NULL,
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE categorias (
  id BIGSERIAL PRIMARY KEY,
  nome VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE solicitacoes (
  id BIGSERIAL PRIMARY KEY,
  titulo VARCHAR(255) NOT NULL,
  descricao TEXT NOT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'ABERTA',
  categoria_id BIGINT NOT NULL REFERENCES categorias(id),
  usuario_id BIGINT NOT NULL REFERENCES usuarios(id),
  data_criacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  data_atualizacao TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO categorias (nome) VALUES ('TI'), ('RH'), ('COMPRAS'), ('FINANCEIRO'), ('INFRAESTRUTURA');
