server: 
  port: 8080

spring: 
  application:
    name: portal-solicitacoes

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/portal_solicitacoes}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgrespassword}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource: true
    properties:
      hibernate:
        format_sql: true
  
  sql:
    init:
      mode: always