import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SideMenu from "@/components/SideMenu";
import Header from "@/components/Header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portal de Solicitações",
  description: "Generated by create next app",
};

export default function PortalLayout({ children }: Readonly<{children: React.ReactNode}>) {
  return (
    <div className="flex h-screen">
      <aside className="w-64 shrink-0 h-screen">
        <SideMenu />
      </aside>
      <div className="flex flex-1 min-w-0 flex-col">
        <Header />
        <main className="flex-1 overflow-y-auto">
          {children}
        </main>
      </div>
    </div>
  );
}
