import type { Metadata } from "next";
import { cookies } from "next/headers";
import { Geist, Geist_Mono } from "next/font/google";

import "../globals.css";

import PortalShell from "@/components/PortalShell";
import { buscarUsuarioId } from "@/services/usuarios";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Portal de Solicitações",
  description: "Generated by create next app",
};

export default async function PortalLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("token")?.value;

  if(!token) {
    return null;
  }

  const payload = JSON.parse(Buffer.from(token.split(".")[1], "base64url").toString());
  const usuarioId = Number(payload.sub);
  const usuario = await buscarUsuarioId(usuarioId);

  return (
    <PortalShell usuario={usuario}>
      {children}
    </PortalShell>
  );
}